baseurl = "http://www.matthewsigal.com/"
title = "Matthew J. Sigal"
copyright = "&copy; 2016 Matthew J. Sigal"
theme = "hugo-academic"
enableEmoji = true
footnotereturnlinkcontents = "<sup>^</sup>"
uglyURLs = true

# Enable comments by entering your Disqus shortname
disqusShortname = "matthew-sigal"

# Enable analytics by entering your Google Analytics tracking ID
googleAnalytics = "UA-101644129-1"

# Default language to use (if you setup multilingual support)
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

# Ignore files
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[blackfriday]
  hrefTargetBlank = true

[params]
  name = "Matthew J. Sigal, PhD"
  role = "Lecturer"
  organization = "Simon Fraser University"
  organization_url = "http://www.sfu.ca/"
  avatar = "me.jpg"
  email = "msigal@sfu.ca"
  address = "6155 RCB Hall, Simon Fraser University, 8888 University Drive, Burnaby, British Columbia, Canada, V5A 1S6."
#  office_hours = "Please email for an appointment."
  phone = "(778) 782-5873"
  skype = ""
  telegram = ""

  # Date format (refer to Go's date format: http://flippinggodateformat.com )
  date_format = "2006-01-02"

  # Enable global LaTeX math rendering?
  math = true

  # Highlight.js options
  #   highlight
  #     Enable global source code highlighting?  If false, you can
  #     override it for a particular page in that page's preamble.
  #
  #     Example: highlight = true
  #
  #   highlight_languages
  #     Add support for highlighting additional languages. Support for
  #     languages mentioned here will be included in all pages. You
  #     can also set this variable for a particular page in that
  #     page's preamble.
  #
  #     Example: highlight_languages = ["go", "lisp", "ocaml"]
  #
  #   highlight_style
  #     Choose a different CSS style for highlighting source
  #     code. Setting this option in a page's preamble has no
  #     effect.
  #
  #     Example: highlight_style = "github-gist"
  #
  #   highlight_version
  #     Choose the version of highlight.js you want. Setting this
  #     option in a page's preamble has no effect.
  #
  #     Example: highlight_version = "9.9.0"
  #
  #   For the list of supported languages, styles, and versions, see:
  #   https://cdnjs.com/libraries/highlight.js/
  #
  #   For more info on the highlighting options, see:
  #   https://gcushen.github.io/hugo-academic-demo/post/writing-markdown-latex/#highlighting-options
  highlight = true
  highlight_languages = ["r"]
  # highlight_style = "github"
  # highlight_version = "9.9.0"

  # Enable native social sharing buttons?
  sharing = false

  # Link custom CSS and JS assets
  #   (relative to /static/css and /static/js respectively)
  custom_css = ["override.css"]
  custom_js  = []

  # Publication types.
  publication_types = [
    'Uncategorized',  # 0
    'Conference proceedings',  # 1
    'Journal',  # 2
    'Work in progress',  # 3
    'Technical report',  # 4
    'Book',  # 5
    'Book chapter'  # 6
  ]

  # Social/Academic Networking
  #
  # Icon pack "fa" includes the following social network icons:
  #   twitter, weibo, linkedin, github, facebook, pinterest, google-plus,
  #   youtube, instagram, soundcloud
  #   Full list: https://fortawesome.github.io/Font-Awesome/icons/
  #
  # Icon pack "ai" includes the following academic network icons:
  #   google-scholar, arxiv, orcid, researchgate, mendeley
  #   Full list: https://jpswalsh.github.io/academicons/

  [[params.social]]
    icon = "envelope"
    icon_pack = "fa"
    link = "mailto:msigal@sfu.ca"
  
  [[params.social]]
    icon = "github"
    icon_pack = "fa"
    link = "//github.com/mattsigal"
  
  [[params.social]]
    icon = "twitter"
    icon_pack = "fa"
    link = "//twitter.com/TwitchCity"

# Navigation Links

[[menu.main]]
  name = "Home"
  url = "#about"
  weight = 1

[[menu.main]]
  name = "Publications"
  url = "#publications"
  weight = 2
  
[[menu.main]]
  name = "Presentations"
  url = "#talks"
  weight = 3

[[menu.main]]
  name = "Teaching"
  url = "#teaching"
  weight = 4

[[menu.main]]
  name = "Scholarships & Awards"
  url = "#Scholarships"
  weight = 5
  
[[menu.main]]
  name = "Posts"
  url = "#posts"
  weight = 6

[[menu.main]]
  name = "Contact"
  url = "#contact"
  weight = 7

# Taxonomies.
[taxonomies]
  tag = "tags"
  category = "categories"
  publication_type = "publication_types"
  
# Languages
#   Create a [languages.X] block for each language you want, where X is the language ID.

# Configure the English version of the website.
[languages.en]
  languageCode = "en-us"
  
